name: Setup Node
description: "Realiza o setup do NPM, Yarn ou semelhante"

inputs:
  node_token:
      description: "Versao"
      required: false
      default: ''
  working_directory:
    description: 'Diretorio de trabalho padrao'
    required: false
    default: '.'
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
  package-manager:
    description: 'Package manager. padrao: yarn'
    required: true
  node-version:
    description: 'Versao do Node. padrao: 21'
    required: false
    default: '21'
  lint-command:
    description: 'Comando do lint. padrao: lint'
    required: false
    default: 'lint'
  install-args:
    description: 'Argumentos extras para instalacao.'
    required: false
    default: ''
  registry_url:
    description: 'URL do registry privado. Opcional'
    required: false
    default: 'https://npm.pkg.github.com'
  scope:
    description: 'Scope para registry privado. Opcional'
    required: false
    default: '@caju-beneficios'
  cache_path:
    required: false
    description: "Path to cache"
  always_auth:
    description: ''
    required: false
    default: 'false'
  
runs:
  using: composite
  steps:

    - name: Setup Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.build_tool }}
        cache-dependency-path: ${{ inputs.cache_path }}
        always-auth: ${{ inputs.always_auth }}
        registry-url: ${{ inputs.registry_url }}
        scope: ${{ inputs.scope }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_token }}
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/*lock*') }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        case "${{ inputs.package-manager }}" in
          npm)
            echo "Package suportado: ${{ inputs.package-manager }}"
            npm ci ${{ inputs.install-args }}
            ;;
          yarn)
            echo "Package suportado: ${{ inputs.package-manager }}"
            yarn install ${{ inputs.install-args }}
            ;;
          pnpm)
            echo "Package suportado: ${{ inputs.package-manager }}"
            pnpm install ${{ inputs.install-args }}
            ;;
          *)
            echo "Package nao suportado: ${{ inputs.package-manager }}"
            ;;
        esac
    